"""自动生成：Forebet 各场赛前预测（1X2 概率 / 预测比分 / 场均进球 / 赔率）。

请勿手工编辑。由 scripts_gen_forebet.py 抓取 forebet.com 列表页解析生成。
数据来源：forebet.com。
"""

null = None  # 兼容 JSON 字面量中的 null（缺失值）

FOREBET_RAW = [
    {
        "match_id": 2463178,
        "home_en": "Bosnia-Herzegovina",
        "away_en": "Qatar",
        "home_cn": "波黑",
        "away_cn": "卡塔尔",
        "url": "https://www.forebet.com/en/football/matches/bosnia-herzegovina-qatar-2463178",
        "p_home": 50,
        "p_draw": 32,
        "p_away": 18,
        "pred_sign": "1",
        "score_home": 2,
        "score_away": 0,
        "avg_goals": 2.15,
        "venue": "Seattle Stadium",
        "date": "24/06/2026 21:00",
        "odds_home": "-250",
        "odds_draw": "+400",
        "odds_away": "+600"
    },
    {
        "match_id": 2463180,
        "home_en": "Morocco",
        "away_en": "Haiti",
        "home_cn": "摩洛哥",
        "away_cn": "海地",
        "url": "https://www.forebet.com/en/football/matches/morocco-haiti-2463180",
        "p_home": 38,
        "p_draw": 32,
        "p_away": 30,
        "pred_sign": "1",
        "score_home": 1,
        "score_away": 0,
        "avg_goals": 0.17,
        "venue": "Atlanta Stadium",
        "date": "25/06/2026 00:00",
        "odds_home": "-625",
        "odds_draw": "+650",
        "odds_away": "+1400"
    },
    {
        "match_id": 2463186,
        "home_en": "Japan",
        "away_en": "Sweden",
        "home_cn": "日本",
        "away_cn": "瑞典",
        "url": "https://www.forebet.com/en/football/matches/japan-sweden-2463186",
        "p_home": 39,
        "p_draw": 30,
        "p_away": 31,
        "pred_sign": "1",
        "score_home": 1,
        "score_away": 0,
        "avg_goals": null,
        "venue": "Dallas Stadium",
        "date": "26/06/2026 01:00",
        "odds_home": "+100",
        "odds_draw": "+230",
        "odds_away": "+300"
    },
    {
        "match_id": 2463192,
        "home_en": "Cape Verde",
        "away_en": "Saudi Arabia",
        "home_cn": "佛得角",
        "away_cn": "沙特阿拉伯",
        "url": "https://www.forebet.com/en/football/matches/cape-verde-saudi-arabia-2463192",
        "p_home": 37,
        "p_draw": 33,
        "p_away": 31,
        "pred_sign": "1",
        "score_home": 1,
        "score_away": 0,
        "avg_goals": null,
        "venue": "Houston Stadium",
        "date": "27/06/2026 02:00",
        "odds_home": "+162",
        "odds_draw": "+225",
        "odds_away": "+175"
    },
    {
        "match_id": 2463190,
        "home_en": "Senegal",
        "away_en": "Iraq",
        "home_cn": "塞内加尔",
        "away_cn": "伊拉克",
        "url": "https://www.forebet.com/en/football/matches/senegal-iraq-2463190",
        "p_home": 66,
        "p_draw": 20,
        "p_away": 14,
        "pred_sign": "1",
        "score_home": 2,
        "score_away": 0,
        "avg_goals": 2.35,
        "venue": "Toronto Stadium",
        "date": "26/06/2026 21:00",
        "odds_home": "-455",
        "odds_draw": "+600",
        "odds_away": "+1000"
    },
    {
        "match_id": 2463198,
        "home_en": "DR Congo",
        "away_en": "Uzbekistan",
        "home_cn": "刚果民主共和国",
        "away_cn": "乌兹别克斯坦",
        "url": "https://www.forebet.com/en/football/matches/dr-congo-uzbekistan-2463198",
        "p_home": 42,
        "p_draw": 30,
        "p_away": 28,
        "pred_sign": "1",
        "score_home": 2,
        "score_away": 0,
        "avg_goals": 2.1,
        "venue": "Atlanta Stadium",
        "date": "28/06/2026 01:30",
        "odds_home": "-149",
        "odds_draw": "+280",
        "odds_away": "+425"
    },
    {
        "match_id": 2467078,
        "home_en": "Brazil",
        "away_en": "Japan",
        "home_cn": "巴西",
        "away_cn": "日本",
        "url": "https://www.forebet.com/en/football/matches/brazil-japan-2467078",
        "p_home": 48,
        "p_draw": 28,
        "p_away": 24,
        "pred_sign": "1",
        "score_home": 3,
        "score_away": 1,
        "avg_goals": 3.63,
        "venue": "Houston Stadium",
        "date": "29/06/2026 19:00",
        "odds_home": "-152",
        "odds_draw": "+275",
        "odds_away": "+425"
    },
    {
        "match_id": 2467080,
        "home_en": "USA",
        "away_en": "Bosnia-Herzegovina",
        "home_cn": "美国",
        "away_cn": "波黑",
        "url": "https://www.forebet.com/en/football/matches/usa-bosnia-herzegovina-2467080",
        "p_home": 47,
        "p_draw": 36,
        "p_away": 17,
        "pred_sign": "1",
        "score_home": 1,
        "score_away": 0,
        "avg_goals": 1.75,
        "venue": "San Francisco Bay Area Stadium",
        "date": "02/07/2026 02:00",
        "odds_home": "-278",
        "odds_draw": "+400",
        "odds_away": "+750"
    },
    {
        "match_id": 2463153,
        "home_en": "Czech Republic",
        "away_en": "South Africa",
        "home_cn": "捷克",
        "away_cn": "南非",
        "url": "https://www.forebet.com/en/football/matches/czech-republic-south-africa-2463153",
        "p_home": 50,
        "p_draw": 29,
        "p_away": 21,
        "pred_sign": "1",
        "score_home": 2,
        "score_away": 0,
        "avg_goals": null,
        "venue": "Atlanta Stadium",
        "date": "18/06/2026 18:00",
        "odds_home": "-125",
        "odds_draw": "+260",
        "odds_away": "+350"
    },
    {
        "match_id": 2463156,
        "home_en": "Mexico",
        "away_en": "South Korea",
        "home_cn": "墨西哥",
        "away_cn": "韩国",
        "url": "https://www.forebet.com/en/football/matches/mexico-south-korea-2463156",
        "p_home": 44,
        "p_draw": 33,
        "p_away": 23,
        "pred_sign": "1",
        "score_home": null,
        "score_away": null,
        "avg_goals": null,
        "venue": "Guadalajara Stadium",
        "date": "19/06/2026 03:00",
        "odds_home": "+110",
        "odds_draw": "+220",
        "odds_away": "+275"
    },
    {
        "match_id": 2463155,
        "home_en": "Canada",
        "away_en": "Qatar",
        "home_cn": "加拿大",
        "away_cn": "卡塔尔",
        "url": "https://www.forebet.com/en/football/matches/canada-qatar-2463155",
        "p_home": 52,
        "p_draw": 35,
        "p_away": 13,
        "pred_sign": "1",
        "score_home": 2,
        "score_away": 0,
        "avg_goals": 2.25,
        "venue": "Vancouver Stadium",
        "date": "19/06/2026 00:00",
        "odds_home": "-357",
        "odds_draw": "+475",
        "odds_away": "+900"
    },
    {
        "match_id": 2463157,
        "home_en": "USA",
        "away_en": "Australia",
        "home_cn": "美国",
        "away_cn": "澳大利亚",
        "url": "https://www.forebet.com/en/football/matches/usa-australia-2463157",
        "p_home": 43,
        "p_draw": 31,
        "p_away": 27,
        "pred_sign": "1",
        "score_home": 1,
        "score_away": 0,
        "avg_goals": null,
        "venue": "Seattle Stadium",
        "date": "19/06/2026 21:00",
        "odds_home": "-182",
        "odds_draw": "+333",
        "odds_away": "+450"
    },
    {
        "match_id": 2463159,
        "home_en": "Brazil",
        "away_en": "Haiti",
        "home_cn": "巴西",
        "away_cn": "海地",
        "url": "https://www.forebet.com/en/football/matches/brazil-haiti-2463159",
        "p_home": 74,
        "p_draw": 16,
        "p_away": 10,
        "pred_sign": "1",
        "score_home": 4,
        "score_away": 0,
        "avg_goals": null,
        "venue": "Philadelphia Stadium",
        "date": "20/06/2026 02:30",
        "odds_home": "-1250",
        "odds_draw": "+1000",
        "odds_away": "+2200"
    },
    {
        "match_id": 2463162,
        "home_en": "Germany",
        "away_en": "Ivory Coast",
        "home_cn": "德国",
        "away_cn": "科特迪瓦",
        "url": "https://www.forebet.com/en/football/matches/germany-ivory-coast-2463162",
        "p_home": 60,
        "p_draw": 28,
        "p_away": 12,
        "pred_sign": "1",
        "score_home": 3,
        "score_away": 0,
        "avg_goals": null,
        "venue": "Toronto Stadium",
        "date": "20/06/2026 22:00",
        "odds_home": "-227",
        "odds_draw": "+375",
        "odds_away": "+550"
    },
    {
        "match_id": 2463165,
        "home_en": "Spain",
        "away_en": "Saudi Arabia",
        "home_cn": "西班牙",
        "away_cn": "沙特阿拉伯",
        "url": "https://www.forebet.com/en/football/matches/spain-saudi-arabia-2463165",
        "p_home": 43,
        "p_draw": 37,
        "p_away": 20,
        "pred_sign": "1",
        "score_home": 2,
        "score_away": 0,
        "avg_goals": 2.25,
        "venue": "Atlanta Stadium",
        "date": "21/06/2026 18:00",
        "odds_home": "-1000",
        "odds_draw": "+900",
        "odds_away": "+2200"
    },
    {
        "match_id": 2463167,
        "home_en": "Uruguay",
        "away_en": "Cape Verde",
        "home_cn": "乌拉圭",
        "away_cn": "佛得角",
        "url": "https://www.forebet.com/en/football/matches/uruguay-cape-verde-2463167",
        "p_home": 42,
        "p_draw": 32,
        "p_away": 26,
        "pred_sign": "1",
        "score_home": 1,
        "score_away": 0,
        "avg_goals": 1.1,
        "venue": "Miami Stadium",
        "date": "22/06/2026 00:00",
        "odds_home": "-250",
        "odds_draw": "+333",
        "odds_away": "+800"
    },
    {
        "match_id": 2463166,
        "home_en": "Belgium",
        "away_en": "Iran",
        "home_cn": "比利时",
        "away_cn": "伊朗",
        "url": "https://www.forebet.com/en/football/matches/belgium-iran-2463166",
        "p_home": 45,
        "p_draw": 31,
        "p_away": 24,
        "pred_sign": "1",
        "score_home": 2,
        "score_away": 1,
        "avg_goals": 2.63,
        "venue": "Los Angeles Stadium",
        "date": "21/06/2026 21:00",
        "odds_home": "-250",
        "odds_draw": "+375",
        "odds_away": "+700"
    },
    {
        "match_id": 2463170,
        "home_en": "France",
        "away_en": "Iraq",
        "home_cn": "法国",
        "away_cn": "伊拉克",
        "url": "https://www.forebet.com/en/football/matches/france-iraq-2463170",
        "p_home": 70,
        "p_draw": 21,
        "p_away": 9,
        "pred_sign": "1",
        "score_home": null,
        "score_away": null,
        "avg_goals": null,
        "venue": "Philadelphia Stadium",
        "date": "22/06/2026 23:00",
        "odds_home": "-1429",
        "odds_draw": "+1100",
        "odds_away": "+2800"
    },
    {
        "match_id": 2463169,
        "home_en": "Argentina",
        "away_en": "Austria",
        "home_cn": "阿根廷",
        "away_cn": "奥地利",
        "url": "https://www.forebet.com/en/football/matches/argentina-austria-2463169",
        "p_home": 56,
        "p_draw": 30,
        "p_away": 14,
        "pred_sign": "1",
        "score_home": null,
        "score_away": null,
        "avg_goals": null,
        "venue": "Dallas Stadium",
        "date": "22/06/2026 19:00",
        "odds_home": "-222",
        "odds_draw": "+333",
        "odds_away": "+650"
    },
    {
        "match_id": 2463173,
        "home_en": "Portugal",
        "away_en": "Uzbekistan",
        "home_cn": "葡萄牙",
        "away_cn": "乌兹别克斯坦",
        "url": "https://www.forebet.com/en/football/matches/portugal-uzbekistan-2463173",
        "p_home": 57,
        "p_draw": 23,
        "p_away": 21,
        "pred_sign": "1",
        "score_home": 2,
        "score_away": 1,
        "avg_goals": null,
        "venue": "Houston Stadium",
        "date": "23/06/2026 19:00",
        "odds_home": "-714",
        "odds_draw": "+750",
        "odds_away": "+1600"
    },
    {
        "match_id": 2463174,
        "home_en": "England",
        "away_en": "Ghana",
        "home_cn": "英格兰",
        "away_cn": "加纳",
        "url": "https://www.forebet.com/en/football/matches/england-ghana-2463174",
        "p_home": 75,
        "p_draw": 14,
        "p_away": 11,
        "pred_sign": "1",
        "score_home": 3,
        "score_away": 0,
        "avg_goals": 3.15,
        "venue": "Boston Stadium",
        "date": "23/06/2026 22:00",
        "odds_home": "-556",
        "odds_draw": "+650",
        "odds_away": "+1400"
    }
]
